version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  flask:
    build: ./api
    image: tetris_api:latest
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./api:/usr/api
    expose:
      - "5000"

  db:
    build: ./db
    image: tetris_db:latest
    restart: always
    expose:
      - "5432"

  game_deploy:
    build: ./tetris
    image: tetris_game_deploy:latest
    restart: always
    depends_on:
      - nginx
    volumes:
      - ./tetris/build:/usr/src/tetris
    expose:
      - "5000"
