version: '3'
services:
  nginx:
    image: cgironalas/tetris_proxy:latest
    restart: always
    ports:
      - "8888:80"

  db:
    image: cgironalas/tetris_db:latest
    restart: always
    expose:
      - "5432"

  flask:
    image: cgironalas/tetris_api:latest
    restart: always
    expose:
      - "5000"
    depends_on:
      - nginx

  game:
    image: cgironalas/tetris_game:latest
    restart: always
    expose:
      - "3000"
    depends_on:
      - nginx
      - db
      - flask
