version: '3'
services:
  api:
    image: cgironalas/tetris_api:latest
    restart: always
    expose:
      - "5000"
    ports:
      - "5000:5000"

  db:
    image: cgironalas/tetris_db:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"


  game:
    image: cgironalas/tetris_game:latest
    restart: always
    expose:
      - "3000"
    ports:
      - "3000:3000"
