version: '3'
services:
  db:
    image: tetris_db:latest
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"

  api:
    image: tetris_api:latest
    restart: always
    volumes:
      - ./api:/usr/api
    expose:
      - "5000"
    ports:
      - "5000:5000"

  game:
    image: tetris_game:latest
    restart: always
    volumes:
      - ./tetris:/usr/src/tetris
    expose:
      - "3000"
    ports:
      - "3000:3000"
