version: '3'
services:
  flask:
    build: ./api
    image: tetris_api:latest
    restart: always
    volumes:
      - ./api:/usr/api
    expose:
      - "5000"

  db:
    build: ./db
    image: tetris_db:latest
    restart: always
    expose:
      - "5432"

  game:
    build: ./tetris
    image: tetris_game:latest
    restart: always
    volumes:
      - ./tetris:/usr/src/tetris
    expose:
      - "3000"
    ports:
      - "8888:3000"
