DROP TABLE IF EXISTS Leaderboard;

CREATE TABLE Leaderboard (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  score INTEGER NOT NULL,
  dateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
